<?php

declare(strict_types=1);

return [
    [
        'id' => 'AUD-ARC-001',
        'name' => 'Business logic in controllers',
        'domain' => 'architecture',
        'severity' => 'medium',
        'confidence' => 'medium',
        'description' => 'A controller action contains substantial business logic (rules, calculations, orchestration) rather than delegating it.',
        'why_it_matters' => 'Controllers that hold business logic are hard to test in isolation and become tangled as the application grows.',
        'recommendation' => 'Extract the logic into a focused class (action/service/form-request) or a domain method on the model, keeping the controller as a thin HTTP adapter.',
        'evidence' => [
            'The controller file and the size/complexity of the action.',
            'Where the extracted logic should live.',
        ],
        'false_positive_considerations' => [
            'Small amounts of glue code are normal and acceptable in a controller.',
            'Do not recommend "move everything into services" or "repository for every model" — these are cargo-cult patterns.',
            'Report only when the logic is substantial, duplicated, or clearly testable in isolation.',
        ],
        'references' => [
            'https://laravel.com/docs/architecture-concepts',
        ],
        'applicability' => [],
    ],
    [
        'id' => 'AUD-ARC-002',
        'name' => 'Duplicated business logic',
        'domain' => 'architecture',
        'severity' => 'medium',
        'confidence' => 'high',
        'description' => 'The same business rule or behavior is implemented in multiple places with the risk of divergence.',
        'why_it_matters' => 'Duplicated logic drifts over time, causing inconsistent behavior and bugs that are fixed in one place but not another.',
        'recommendation' => 'Extract the shared behavior into a single well-tested location and reuse it from all call sites.',
        'evidence' => [
            'Two or more locations implementing the same rule.',
            'The extracted single source of truth that should be used.',
        ],
        'false_positive_considerations' => [
            'Occasional small similarities are not duplication.',
            'The copies may be intentionally different variants.',
        ],
        'references' => [],
        'applicability' => [],
    ],
    [
        'id' => 'AUD-ARC-003',
        'name' => 'Unnecessary abstraction',
        'domain' => 'architecture',
        'severity' => 'low',
        'confidence' => 'medium',
        'description' => 'An abstraction layer (interface, repository, service, factory) adds indirection without providing real value such as testability, swap-ability, or reused behavior.',
        'why_it_matters' => 'Unneeded abstractions increase maintenance cost and make code harder to follow without adding benefits.',
        'recommendation' => 'Remove the abstraction and use the concrete class directly unless a real extension point is needed.',
        'evidence' => [
            'The abstraction and all its implementations/usages.',
            'Why the abstraction does not currently provide value.',
        ],
        'false_positive_considerations' => [
            'An interface may be justified by an upcoming swap or testing need.',
            'Deferring judgement on common-but-debated patterns (service layer) unless they demonstrably add complexity.',
        ],
        'references' => [],
        'applicability' => [],
    ],
    [
        'id' => 'AUD-ARC-004',
        'name' => 'Application boundary violation',
        'domain' => 'architecture',
        'severity' => 'medium',
        'confidence' => 'medium',
        'description' => 'Domain or persistence concerns leak into routes, views, or middleware, or HTTP/presentation concerns leak into models or jobs.',
        'why_it_matters' => 'Broken boundaries make behavior hard to test and change without unexpected side effects.',
        'recommendation' => 'Keep HTTP adapters thin, keep domain rules out of views, and keep persistence details out of presentation layers.',
        'evidence' => [
            'The leaking class/file and the layer it should belong to.',
        ],
        'false_positive_considerations' => [
            'Small apps may keep simple queries in controllers without it being a problem.',
        ],
        'references' => [
            'https://laravel.com/docs/structure',
        ],
        'applicability' => [],
    ],
    [
        'id' => 'AUD-ARC-005',
        'name' => 'Inconsistent architectural convention',
        'domain' => 'architecture',
        'severity' => 'low',
        'confidence' => 'medium',
        'description' => 'The codebase mixes incompatible conventions for the same kind of work (actions vs services vs fat controllers) without a documented reason, creating maintenance friction.',
        'why_it_matters' => 'Inconsistent structure slows onboarding and makes the next change harder than it should be.',
        'recommendation' => 'Pick the convention the codebase already uses most and apply it to new work. Do not introduce a new layer just for consistency theater.',
        'evidence' => [
            'Two or more conflicting conventions and the feature they implement.',
        ],
        'false_positive_considerations' => [
            'A gradual migration may intentionally mix old and new styles.',
        ],
        'references' => [],
        'applicability' => [],
    ],
    [
        'id' => 'AUD-ARC-006',
        'name' => 'Oversized class or long method',
        'domain' => 'architecture',
        'severity' => 'medium',
        'confidence' => 'medium',
        'description' => 'A single class or method (controller action, job handle, Livewire component, Filament resource, Eloquent model) carries several responsibilities or a long sequential procedure that is hard to test and change in isolation.',
        'why_it_matters' => 'Oversized units change for several reasons at once, so every edit risks unrelated behavior and tests must cover the whole unit to verify one path.',
        'recommendation' => 'Apply Extract Method / Extract Class: split the unit along its distinct responsibilities into focused collaborators that fit the existing style, keeping the entry point as a thin orchestrator.',
        'evidence' => [
            'The class/method file and line range plus the distinct responsibilities it currently mixes.',
            'A change scenario that would force touching the same unit for unrelated reasons.',
        ],
        'false_positive_considerations' => [
            'A long cohesive procedure with a single reason to change (for example a migration or a declarative Filament schema) is not oversized.',
            'A resource controller with several thin actions is normal; report only when one class or method mixes responsibilities.',
            'Do not split code merely to reduce line counts.',
        ],
        'references' => [
            'https://refactoring.guru/smells/long-method',
            'https://refactoring.guru/smells/large-class',
        ],
        'applicability' => [],
    ],
    [
        'id' => 'AUD-ARC-007',
        'name' => 'Primitive obsession, data clumps, or long parameter list',
        'domain' => 'architecture',
        'severity' => 'low',
        'confidence' => 'medium',
        'description' => 'Related scalars travel together as loose primitives: stringly-typed statuses, parallel arrays, or groups of 4+ scalar parameters passed as a set in more than one place instead of a value object, enum, or DTO.',
        'why_it_matters' => 'Loose primitives let invalid combinations compile and force every call site to repeat validation, formatting, and ordering assumptions that drift over time.',
        'recommendation' => 'Apply Introduce Parameter Object / Replace Primitive with Object: group the clump into an enum, value object, form request, or DTO the codebase already uses, without adding a new architectural layer.',
        'evidence' => [
            'Two or more call sites passing the same primitive group, or the repeated validation/formatting of the same loose values.',
            'The enum, value object, or DTO that should own the group.',
        ],
        'false_positive_considerations' => [
            'Independent flags that truly combine freely are not a clump (see AUD-DSA-001 for invalid combinations).',
            'A single call site with several scalars is a signature smell, not a finding on its own.',
            'Do not invent a shared type for values that only look similar but mean different things.',
        ],
        'references' => [
            'https://refactoring.guru/smells/primitive-obsession',
            'https://refactoring.guru/smells/data-clumps',
            'https://refactoring.guru/smells/long-parameter-list',
        ],
        'applicability' => [],
    ],
    [
        'id' => 'AUD-ARC-008',
        'name' => 'Adding a variant requires editing core code',
        'domain' => 'architecture',
        'severity' => 'medium',
        'confidence' => 'medium',
        'description' => 'Adding one variant (provider, format, handler, notification channel, report type) forces edits across core code: copied type-tag switches, hardcoded lists of built-in variants, or shotgun edits in several unrelated files.',
        'why_it_matters' => 'Every new case risks a missed call site, so behavior diverges and the change touches places unrelated to the new variant.',
        'recommendation' => 'Apply Replace Conditional with Polymorphism: collapse the copied switches into one registry, map, or contract the codebase already uses. A plain array is enough unless a real extension point is needed.',
        'evidence' => [
            'Two or more switches or conditionals over the same variant set, or the list of files changed to add the last variant.',
            'The registry, map, or contract that should own the variant set.',
        ],
        'false_positive_considerations' => [
            'A single switch in one file is already the simple model (see AUD-DSA-003).',
            'A closed set of two or three stable cases with no history of growth is not an extension point.',
            'Do not add an interface when a plain array removes the duplication.',
        ],
        'references' => [
            'https://refactoring.guru/smells/switch-statements',
            'https://refactoring.guru/smells/shotgun-surgery',
            'https://refactoring.guru/smells/divergent-change',
        ],
        'applicability' => [],
    ],
    [
        'id' => 'AUD-ARC-009',
        'name' => 'Feature envy, message chains, or inappropriate intimacy',
        'domain' => 'architecture',
        'severity' => 'medium',
        'confidence' => 'medium',
        'description' => 'A method uses another module internals more than its own: long message chains (`$order->user->profile->...`), repeated reaches into related models, or reliance on mutable internal state that should stay private.',
        'why_it_matters' => 'Couplers spread change impact across modules, hide null and N+1 failures behind templates, and make the behavior untestable without the full graph.',
        'recommendation' => 'Apply Move Method / Hide Delegate: move the behavior to the module that owns the data, or expose one intention-revealing method instead of the chain. Trace the full path before recommending.',
        'evidence' => [
            'The envying method and the chain or internal state it reaches through.',
            'The owning module that should expose the behavior instead.',
            'What actually happens at runtime when an intermediate link is null or unloaded.',
        ],
        'false_positive_considerations' => [
            'Fluent Eloquent and query builder chains are idiomatic and not message chains.',
            'A single delegated call is normal; require a chain or repeated reaches into foreign state.',
            'Anemic getters used once by a view are a layering choice, not envy on their own.',
        ],
        'references' => [
            'https://refactoring.guru/smells/feature-envy',
            'https://refactoring.guru/smells/message-chains',
            'https://refactoring.guru/smells/inappropriate-intimacy',
            'https://refactoring.guru/smells/middle-man',
        ],
        'applicability' => [],
    ],
    [
        'id' => 'AUD-ARC-010',
        'name' => 'Dead code or speculative generality',
        'domain' => 'architecture',
        'severity' => 'low',
        'confidence' => 'medium',
        'description' => 'Code, abstractions, or configuration options with no reachable callers: unused classes, methods, Blade components, routes, config keys, or speculative extension points added for a future that never arrived.',
        'why_it_matters' => 'Dead code misleads readers and reviewers, keeps untested paths in the security surface, and makes every later change consider behavior that never runs.',
        'recommendation' => 'Delete the dead unit and its tests, docs, and config entries. Prefer deletion over deprecation for unreleased speculative code.',
        'evidence' => [
            'The dead definition with file and line references.',
            'Grep proof of zero references across source, tests, routes, config, Blade views, and docs, allowing for route or DI auto-wiring, events, policies, and string-based lookups.',
        ],
        'false_positive_considerations' => [
            'Framework conventions (route auto-wiring, policies, gates, event listeners, Blade components, queued jobs, scheduled commands) and the public package API are live callers even without a direct PHP reference.',
            'Recently added code awaiting its first caller is not dead; require evidence it was abandoned.',
            'Do not report commented-out blocks as dead code without checking history; report them as comments only when they mislead.',
        ],
        'references' => [
            'https://refactoring.guru/smells/dead-code',
            'https://refactoring.guru/smells/speculative-generality',
            'https://refactoring.guru/smells/lazy-class',
        ],
        'applicability' => [],
    ],
    [
        'id' => 'AUD-ARC-011',
        'name' => 'Inconsistent sibling contracts or silent extension defaults',
        'domain' => 'architecture',
        'severity' => 'low',
        'confidence' => 'medium',
        'description' => 'Sibling implementations give the same concept different meanings (null versus empty, units, ID formats, error handling), or a plugin, driver, or hook falls back to a silent no-op instead of a visible failure when a third-party variant is used.',
        'why_it_matters' => 'Callers cannot trust the contract, so they add defensive branches that spread; silent defaults make third-party extensions appear to work while doing nothing.',
        'recommendation' => 'Align the siblings on the convention the codebase already uses most, or make the extension default explicit (exception, log, or documented no-op). Escalate to medium only when the inconsistency causes a wrong result or the silent default hides a failure.',
        'evidence' => [
            'Two or more siblings with conflicting meanings for the same concept, or the extension point with its silent default path.',
            'A caller that must defend against both meanings, or a third-party variant that receives the silent default.',
        ],
        'false_positive_considerations' => [
            'A documented migration between old and new contracts is intentional inconsistency, not a finding.',
            'Framework-mandated differences (for example nullable database columns versus required request input) are layering, not sibling drift.',
            'Style-only differences without caller impact are info at best.',
        ],
        'references' => [
            'https://refactoring.guru/smells/alternative-classes-with-different-interfaces',
            'https://refactoring.guru/smells/temporary-field',
        ],
        'applicability' => [],
    ],
];
