<?php

declare(strict_types=1);

return [
    [
        'id' => 'AUD-PER-001',
        'name' => 'N+1 query risk',
        'domain' => 'performance',
        'severity' => 'medium',
        'confidence' => 'medium',
        'description' => 'A loop or collection rendering triggers repeated queries for related models without eager loading.',
        'why_it_matters' => 'N+1 queries multiply database round-trips with dataset size and are a common cause of slow pages under real load.',
        'recommendation' => 'Eager load the relationships (e.g. `with("author")`) or use `load` when relationships are needed after querying.',
        'evidence' => [
            'The loop/query site and the relationship being fetched per iteration.',
            'A count of queries or the presence of `with` usage as contrast.',
        ],
        'false_positive_considerations' => [
            'The loop may run over a small fixed set (e.g. a handful of rows).',
            'The relationship may already be cached or loaded by a preceding `with`.',
            'Do not report every loop; require evidence of an actual repeated query.',
        ],
        'references' => [
            'https://laravel.com/docs/eloquent-relationships#eager-loading',
        ],
        'applicability' => [],
    ],
    [
        'id' => 'AUD-PER-002',
        'name' => 'Expensive work in the request lifecycle',
        'domain' => 'performance',
        'severity' => 'low',
        'confidence' => 'medium',
        'description' => 'Expensive, repeatable, or time-consuming work is performed synchronously in the request lifecycle where a queue, cache, or deferred computation is a better fit.',
        'why_it_matters' => 'Synchronous heavy work increases response latency and reduces throughput; repeated expensive computation wastes resources.',
        'recommendation' => 'Move non-essential work to a queued job, memoize/cache expensive computation, or defer it until needed.',
        'evidence' => [
            'The expensive call and its location in the request path.',
            'Why the work is expensive (external API, large computation, I/O).',
        ],
        'false_positive_considerations' => [
            'The work may be necessary for the response and cannot be deferred.',
            'The work may already be cached.',
            'Do not recommend caching without a strong justification.',
        ],
        'references' => [
            'https://laravel.com/docs/queues',
            'https://laravel.com/docs/cache',
        ],
        'applicability' => [],
    ],
    [
        'id' => 'AUD-PER-003',
        'name' => 'Missing index on a frequently-queried column',
        'domain' => 'performance',
        'severity' => 'low',
        'confidence' => 'low',
        'description' => 'A column that is frequently filtered, joined, or ordered by lacks a database index.',
        'why_it_matters' => 'Unindexed lookups degrade to table scans and slow down as the table grows.',
        'recommendation' => 'Add a migration that indexes the column (or composite index) where query patterns justify it.',
        'evidence' => [
            'The column and the queries that filter/join on it.',
            'Schema/migration showing the column lacks an index.',
        ],
        'false_positive_considerations' => [
            'Small tables may not need an index.',
            'The column may already be covered by a composite index.',
            'Require evidence of actual query patterns; do not index every column.',
        ],
        'references' => [
            'https://laravel.com/docs/migrations#creating-indexes',
        ],
        'applicability' => [],
    ],
    [
        'id' => 'AUD-PER-004',
        'name' => 'Repeated query without reuse',
        'domain' => 'performance',
        'severity' => 'low',
        'confidence' => 'medium',
        'description' => 'The same query or expensive lookup is executed multiple times in one request instead of being reused, memoized, or eager-loaded.',
        'why_it_matters' => 'Repeated queries add latency that grows with request complexity and traffic.',
        'recommendation' => 'Reuse the first result, eager-load the relationship, or memoize the lookup for the request lifetime.',
        'evidence' => [
            'Two or more call sites executing the same query in one request path.',
        ],
        'false_positive_considerations' => [
            'The second query may be intentionally different or already cached.',
        ],
        'references' => [
            'https://laravel.com/docs/eloquent',
        ],
        'applicability' => [],
    ],
    [
        'id' => 'AUD-PER-005',
        'name' => 'Synchronous work that belongs on a queue',
        'domain' => 'performance',
        'severity' => 'medium',
        'confidence' => 'medium',
        'description' => 'Email, notifications, remote HTTP, PDF/image processing, or other non-essential I/O runs synchronously in a web request when a queued job is the idiomatic Laravel fit.',
        'why_it_matters' => 'Synchronous side effects make requests slow and fragile when the remote service is down.',
        'recommendation' => 'Dispatch a queued job or notification for work that is not required to produce the HTTP response.',
        'evidence' => [
            'The synchronous call and the request path that contains it.',
        ],
        'false_positive_considerations' => [
            'The user may be waiting on the result, so the work cannot be deferred.',
        ],
        'references' => [
            'https://laravel.com/docs/queues',
        ],
        'applicability' => [],
    ],
    [
        'id' => 'AUD-PER-006',
        'name' => 'Inefficient collection or database usage',
        'domain' => 'performance',
        'severity' => 'low',
        'confidence' => 'medium',
        'description' => 'A large dataset is loaded into a collection and filtered/sorted in PHP, or a query omits pagination/`chunk`/`cursor` where the table can grow. Use the specific rules (AUD-PER-008 materialized aggregates, AUD-PER-009 query-side filtering, AUD-PER-012 unbounded retrieval) when they match; this rule covers remaining misuse.',
        'why_it_matters' => 'Loading unbounded rows wastes memory and time as the table grows.',
        'recommendation' => 'Push filters, sorts, and limits into the query, and paginate or chunk large result sets.',
        'evidence' => [
            'The query/collection site and why the dataset can be large.',
        ],
        'false_positive_considerations' => [
            'A known tiny lookup table does not need pagination.',
        ],
        'references' => [
            'https://laravel.com/docs/pagination',
            'https://laravel.com/docs/eloquent#chunking-results',
        ],
        'applicability' => [],
    ],
    [
        'id' => 'AUD-PER-007',
        'name' => 'Repeated expensive computation without cache',
        'domain' => 'performance',
        'severity' => 'low',
        'confidence' => 'low',
        'description' => 'The same expensive, stable result is recomputed across requests when a cache key and invalidation strategy are clearly justified.',
        'why_it_matters' => 'Uncached repeated work burns CPU and external quota on every request.',
        'recommendation' => 'Cache the result with an explicit key and invalidation path. Do not cache just because a function looks slow.',
        'evidence' => [
            'The expensive computation and proof it is stable enough to cache.',
            'The request paths that recompute it.',
        ],
        'false_positive_considerations' => [
            'Do not recommend caching without a clear key and invalidation story.',
            'User-specific or highly volatile data is usually a poor cache candidate.',
        ],
        'references' => [
            'https://laravel.com/docs/cache',
        ],
        'applicability' => [],
    ],
    [
        'id' => 'AUD-PER-008',
        'name' => 'Aggregate or existence answer computed after materializing rows',
        'domain' => 'performance',
        'severity' => 'medium',
        'confidence' => 'medium',
        'description' => 'A query materializes its results (`get()`, `all()`, full-model `pluck()`) and immediately reduces them to a scalar (`count()`, `isEmpty()`/`isNotEmpty()`, `first()`, `sum()`, `avg()`, `min()`, `max()`) even though the collection has no other consumer in the scope.',
        'why_it_matters' => 'Every matching row is transferred from the database and hydrated into models only to be collapsed into one value. Query-level equivalents (`->count()`, `->exists()`, `->first()`, `->sum()`, aggregate expressions) let the database return a single result instead of every row.',
        'recommendation' => 'Replace the materialize-then-reduce sequence with the query-level equivalent when — and only when — the collection is not used elsewhere. If the collection is also rendered, returned, or transformed, keep it and derive the aggregate from the already-loaded data rather than issuing a second query.',
        'evidence' => [
            'The call site showing the materialize step and the reduction applied to it.',
            'Confirmation that the resulting collection has no other consumer in the method, view, or caller (this is what separates a real finding from AUD-PER-008\'s main false positive).',
            'An indication that the row count can be non-trivial or grow (table purpose, missing limit, user-facing filter).',
        ],
        'false_positive_considerations' => [
            'The collection is reused after the aggregate call — deriving count()/first() from loaded data is cheaper than a second query, so this rule does not apply.',
            'PHP-side semantics differ from SQL semantics: accessors, casts, JSON columns, custom collection classes, and null handling can change results. Verify equivalence before recommending.',
            'Bounded, tiny datasets where both forms are effectively free are micro-optimization noise; do not report them.',
        ],
        'references' => [
            'https://laravel.com/docs/eloquent#aggregates',
            'https://laravel.com/docs/queries#aggregates',
        ],
        'applicability' => [],
    ],
    [
        'id' => 'AUD-PER-009',
        'name' => 'Filtering, sorting, or slicing in PHP that the query can do',
        'domain' => 'performance',
        'severity' => 'medium',
        'confidence' => 'medium',
        'description' => 'Data is retrieved unfiltered or unsorted and then filtered, sorted, or sliced in PHP on freshly queried rows (`get()->where(...)`, `get()->sortBy(...)`, `get()->filter(...)->take(...)`) even though the database could perform the same operation before the transfer.',
        'why_it_matters' => 'Rows that the filter will discard are still transferred and hydrated. Moving selection, ordering, and limiting into the query shrinks both the transfer and the hydration cost, and lets indexes participate.',
        'recommendation' => 'Push `where`, `orderBy`, and `limit`/`take` into the query builder when the semantics match. Verify equivalence explicitly: PHP comparisons are loose by default while SQL comparisons are not, collation affects ordering, callbacks may depend on accessors/casts, and collection `where()` uses loose comparison. Keep the work in PHP when it depends on PHP-only behavior or when the unfiltered collection is genuinely needed afterwards.',
        'evidence' => [
            'The retrieval site and the PHP-side transformation applied to its result.',
            'A statement of why the transformation can (or cannot) move into the query with identical results.',
            'Evidence the discarded-row share matters (row source, growth expectation, hot path).',
        ],
        'false_positive_considerations' => [
            'The filter depends on PHP-only behavior (accessors, casts, custom comparators, loose comparison) that SQL cannot reproduce identically.',
            'The unfiltered collection is needed elsewhere, so filtering at the query level would force a second query.',
            'The dataset is small and bounded; both forms are effectively free.',
        ],
        'references' => [
            'https://laravel.com/docs/queries#where-clauses',
            'https://laravel.com/docs/queries#ordering-grouping-limit-and-offset',
        ],
        'applicability' => [],
    ],
    [
        'id' => 'AUD-PER-010',
        'name' => 'Relationship loaded only to answer count or existence',
        'domain' => 'performance',
        'severity' => 'medium',
        'confidence' => 'medium',
        'description' => 'A model relationship is materialized as a collection solely to answer a count or existence question (`$post->comments->count()`, `$post->comments->isNotEmpty()`), or a loop of such checks loads every related row per parent.',
        'why_it_matters' => 'Loading every related row to produce one number transfers and hydrates rows that are never used. `withCount()`/`withExists()` (batched, one extra column) or `$model->relation()->count()` / `$model->relation()->exists()` (single aggregate query) answer the same question without the transfer.',
        'recommendation' => 'Prefer `withCount()`/`withExists()` when several parents need the answer (it avoids both N+1 and hydration), or the relationship query form for a single model. Do not apply this when the relationship collection is already loaded and used for its records.',
        'evidence' => [
            'The relationship access site and the question it actually answers (count vs existence).',
            'Whether the loaded collection is used for anything besides the scalar answer.',
            'For loops: the number of parents involved or the source of their quantity.',
        ],
        'false_positive_considerations' => [
            'The relationship collection is already eager-loaded and iterated elsewhere — calling ->count()/isEmpty() on it costs nothing further; do not report.',
            'A custom collection class may override count()/contains() with non-trivial behavior; verify before recommending the query form.',
            'A one-off check on a single model with a tiny related set is noise unless the path is hot.',
        ],
        'references' => [
            'https://laravel.com/docs/eloquent-relationships#counting-related-models',
            'https://laravel.com/docs/eloquent-relationships#other-aggregate-functions',
        ],
        'applicability' => [],
    ],
    [
        'id' => 'AUD-PER-011',
        'name' => 'Query executed inside a loop',
        'domain' => 'performance',
        'severity' => 'high',
        'confidence' => 'medium',
        'description' => 'A database query (or other per-item I/O) executes inside a loop body whose iteration count is driven by data: `foreach ($orders as $o) { Order::where(...)->count(); }`, `User::find($id)` per item, `firstOrCreate`/updates per row where bulk forms exist.',
        'why_it_matters' => 'Per-item queries multiply round-trips by iteration count. On user-facing paths this is the classic query explosion; on batch paths it can turn seconds into minutes. The fix depends on intent — there is no single prescribed remedy.',
        'recommendation' => 'Investigate what each iteration actually needs, then choose among eager loading (`with`), counted columns (`withCount`/`withExists`), one bulk fetch keyed by ID with in-memory lookup (`whereIn` + `keyBy`), join/group aggregates, or batched writes (`upsert`, mass updates). Match the alternative to the intent instead of defaulting to one pattern.',
        'evidence' => [
            'The loop and the statement executed per iteration, with the iteration-count driver (query result, collection size, user input).',
            'Why each iteration cannot reuse data fetched outside the loop as-is.',
            'The chosen alternative and why it preserves behavior (ordering, per-row side effects, model events).',
        ],
        'false_positive_considerations' => [
            'Loops over a small fixed set (config-driven constants, a handful of enum values) are usually not worth restructuring.',
            'Per-row inserts that rely on model events/casts may not have a safe bulk equivalent.',
            'Queued consumers draining one item at a time by design are a workload choice, not a loop bug.',
        ],
        'references' => [
            'https://laravel.com/docs/eloquent-relationships#eager-loading',
            'https://laravel.com/docs/queries#where-in-clauses',
            'https://laravel.com/docs/eloquent#upserts',
        ],
        'applicability' => [],
    ],
    [
        'id' => 'AUD-PER-012',
        'name' => 'Unbounded retrieval on a path that can grow',
        'domain' => 'performance',
        'severity' => 'medium',
        'confidence' => 'medium',
        'description' => '`Model::all()` or an unbounded `get()` sits on a path whose dataset grows without application control: API endpoints, exports, reports, scheduled commands, queue jobs, or admin screens — with no pagination, limit, chunking, or streaming step.',
        'why_it_matters' => 'Memory and latency scale with the table. A query that is fine at 5k rows becomes an outage at 500k. The right mechanism depends on how the consumer uses the rows.',
        'recommendation' => 'Choose by workload: `paginate`/`simplePaginate`/`cursorPaginate` for HTTP responses; `lazyById`/`chunkById` for read-modify-write passes over large tables; `lazy`/`cursor` for single-pass reads feeding exports or streams. Do not paginate when the consumer genuinely needs the complete dataset in memory — say so explicitly instead of forcing a mechanism.',
        'evidence' => [
            'The retrieval site, its route/command/job context, and any existing limiting.',
            'Why the underlying table can grow (user-generated rows, imports, log-like data) or proof it is bounded.',
            'How the consumer consumes rows, so the recommended mechanism fits.',
        ],
        'false_positive_considerations' => [
            'Inherently bounded tables (countries, currencies, settings) do not need pagination.',
            'The result may already be constrained elsewhere (`latest()->take()`, date-window filters) — read the full chain first.',
            'CLI tools documented as whole-table processors may be intentional if memory profiles are acceptable; note rather than report.',
        ],
        'references' => [
            'https://laravel.com/docs/pagination',
            'https://laravel.com/docs/eloquent#chunking-results',
            'https://laravel.com/docs/eloquent#streaming-results-lazily',
        ],
        'applicability' => [],
    ],
    [
        'id' => 'AUD-PER-013',
        'name' => 'More columns retrieved than the code consumes',
        'domain' => 'performance',
        'severity' => 'low',
        'confidence' => 'low',
        'description' => 'A query returning many rows selects every column (`select(*)`, default full-model hydration) while downstream code touches only a small subset, particularly when the table carries large TEXT/BLOB/JSON columns.',
        'why_it_matters' => 'Unused wide columns inflate transfer, network I/O, and per-row memory proportionally to row count. Narrowing selection helps most on list endpoints, exports, and dropdown feeds over wide tables.',
        'recommendation' => 'Consider `->select([...])` or `pluck()` for the consumed fields on high-volume, performance-sensitive paths. Verify Eloquent still receives what it needs: the primary key for relations/keying, foreign keys for eager-load matching, and any columns referenced by casts, accessors, or appended attributes.',
        'evidence' => [
            'The query site, the columns actually consumed downstream, and the row volume source.',
            'Schema evidence that unselected columns exist and are wide (from `database_schema`).',
            'Confirmation no accessor/cast/serialization needs the dropped columns.',
        ],
        'false_positive_considerations' => [
            'Models with appended attributes or accessor-dependent serialization often need more columns than the visible code suggests.',
            'Partial models cannot be safely updated or used in some relation flows; selecting subsets has correctness preconditions.',
            'Narrow tables or tiny row counts make this micro-optimization noise; keep it low severity at best.',
        ],
        'references' => [
            'https://laravel.com/docs/queries#selects',
            'https://laravel.com/docs/eloquent#retrieving-models',
        ],
        'applicability' => [],
    ],
    [
        'id' => 'AUD-PER-014',
        'name' => 'Repeated external HTTP requests without batching or reuse',
        'domain' => 'performance',
        'severity' => 'medium',
        'confidence' => 'medium',
        'description' => 'HTTP client calls run inside loops, identical requests repeat within one lifecycle, or independent sequential calls stack latency (`Http::get()` per item, re-fetching the same endpoint in several methods).',
        'why_it_matters' => 'Each call pays connection, TLS, and remote-processing latency serially. Loop-amplified external calls are a leading cause of timeout incidents and exhausted rate limits.',
        'recommendation' => 'Investigate dependency between calls first: independent calls may suit Laravel HTTP concurrency (`Http::pool`) or batching; repeated identical results belong in request-scoped memoization or a cache with TTL; loop-per-item APIs should be checked for a bulk endpoint. Never propose concurrency for calls that depend on earlier responses.',
        'evidence' => [
            'Each call site, the loop containing it, and the dependency graph between calls.',
            'Whether responses are reusable across callers (stability of inputs).',
            'Any rate-limit or auth constraints that constrain the fix.',
        ],
        'false_positive_considerations' => [
            'Sequential calls whose later input depends on earlier output cannot be parallelized.',
            'APIs that punish concurrency or forbid bulk fetches — respect the contract.',
            'One cached or memoized call is fine; only repetition without reuse is a finding.',
        ],
        'references' => [
            'https://laravel.com/docs/http-client#concurrent-requests',
            'https://laravel.com/docs/cache',
        ],
        'applicability' => [],
    ],
    [
        'id' => 'AUD-PER-015',
        'name' => 'Filesystem or storage work repeated or unbuffered',
        'domain' => 'performance',
        'severity' => 'low',
        'confidence' => 'medium',
        'description' => 'Storage/filesystem operations repeat inside loops (existence checks, reads of the same key), or large files load fully into memory (`Storage::get()`, `file_get_contents`) where streaming would fit the processing pattern.',
        'why_it_matters' => 'Remote storage disks turn each call into network I/O, so per-item calls multiply latency. Whole-file reads bound memory usage by file size and can exceed limits on uploads, logs, and exports.',
        'recommendation' => 'Reuse the result of existence checks and reads instead of re-fetching; process large files with streams (`readStream`/`fwrite`, line-by-line readers); move transformations into streamed pipelines for exports and imports. Match the fix to whether the disk is local or remote.',
        'evidence' => [
            'The operation sites and the loop or size driver behind them.',
            'Which filesystem disk is used and whether it is remote (S3 et al.).',
            'File-size expectations for the whole-file-read cases.',
        ],
        'false_positive_considerations' => [
            'Small config/seed files loaded once per request are immaterial.',
            'Local-disk operations on small files rarely justify restructuring.',
            'Some processing genuinely needs the whole file (random access, archive handling); streaming would complicate correctness.',
        ],
        'references' => [
            'https://laravel.com/docs/filesystem#streaming-files',
            'https://www.php.net/manual/en/function.fopen.php',
        ],
        'applicability' => [],
    ],
    [
        'id' => 'AUD-PER-016',
        'name' => 'Queue job processes unbounded data or carries oversized payloads',
        'domain' => 'performance',
        'severity' => 'medium',
        'confidence' => 'medium',
        'description' => 'A queued job loads or iterates an unbounded dataset without chunking, serializes large collections/model graphs into its payload, dispatches one tiny job per row where batch processing fits, or re-fetches the same data repeatedly across a chain.',
        'why_it_matters' => 'Jobs run long by design, but unbounded queries inside a worker can exceed timeouts mid-pass and retry forever, while oversized payloads bloat the queue backend and slow every worker that reads them.',
        'recommendation' => 'Pass identifiers instead of large graphs, process with `chunkById`/`lazyById` inside `Batchable` batches for resumability, group per-row jobs into batched work when ordering does not matter, and keep each job\'s dataset bounded. Only restructure when the workload is actually queue-backed; do not recommend queues automatically.',
        'evidence' => [
            'The job handle()/constructor showing the data loading or payload size.',
            'The expected dataset growth and timeout/retry configuration.',
            'Why the chosen bounding mechanism preserves completion of the whole workload.',
        ],
        'false_positive_considerations' => [
            'Jobs already bounded by construction (single ID, fixed window) are fine.',
            'Small payloads serialized for convenience may be acceptable; require real size evidence.',
            'Per-row jobs can be intentional for isolation/retry granularity — weigh before recommending batches.',
        ],
        'references' => [
            'https://laravel.com/docs/queues#job-batching',
            'https://laravel.com/docs/eloquent#chunking-results',
        ],
        'applicability' => [],
    ],
    [
        'id' => 'AUD-PER-017',
        'name' => 'Rendering path performs queries or repeated expensive work',
        'domain' => 'performance',
        'severity' => 'medium',
        'confidence' => 'medium',
        'description' => 'View rendering triggers database work directly (queries inside Blade loops/components), repeated relationship access without eager loading, expensive helpers recomputed per iteration, or per-render recomputation of stable values with no caching layer in between.',
        'why_it_matters' => 'Render-time queries hide N+1s behind templates and make every page view pay data-access costs that belong in the controller/composer. Work repeated per iteration multiplies silently as datasets grow.',
        'recommendation' => 'Compose the data before rendering: eager load what views iterate, compute aggregates once and pass them down, hoist invariant expressions out of loops, and use view composers or cached fragments where a value is stable across renders. Verify any fragment cache actually covers the expensive path.',
        'evidence' => [
            'The template/component site and the query or computation executed there.',
            'The loop count driver or render frequency that amplifies it.',
            'Proof no existing cache/eager-load layer already covers the cost.',
        ],
        'false_positive_considerations' => [
            'Fragments wrapped in cache directives may never hit the expensive path on warm caches.',
            'A single cheap lookup outside loops is not a rendering problem.',
            'Livewire/Filament have dedicated rules (AUD-LW-003, AUD-FIL-003) — prefer those when applicable.',
        ],
        'references' => [
            'https://laravel.com/docs/blade',
            'https://laravel.com/docs/eloquent-relationships#eager-loading',
        ],
        'applicability' => [],
    ],
    [
        'id' => 'AUD-PER-018',
        'name' => 'Chained collection transformations creating avoidable intermediates',
        'domain' => 'performance',
        'severity' => 'low',
        'confidence' => 'low',
        'description' => 'Collection chains materialize avoidable intermediate arrays or repeat passes over one large collection: `map()->filter()`, `filter()->first()` where `first(callable)` suffices, `sortBy(...)->first()` where a min-by works, or several separate full passes over the same data.',
        'why_it_matters' => 'Each pass allocates and walks the full set again. On large collections in hot paths, collapsing passes removes allocations and iterations — but this is only meaningful at scale, which is why the rule is low severity and evidence-gated.',
        'recommendation' => 'Where semantics are identical, prefer single-pass forms (`first(callable)`, `sum(callable)`, `groupBy` + aggregate) or `lazy` collections for long chains over large sets. Report only when the collection size is plausibly large and the replacement is exactly equivalent — higher-order collection proxies and callback signatures must behave identically to the chain being replaced.',
        'evidence' => [
            'The chained transformation site and the sizes it plausibly handles.',
            'Equivalence reasoning for the proposed single-pass form (callback semantics, key preservation, strictness).',
        ],
        'false_positive_considerations' => [
            'Small collections: collapsing passes is micro-optimization noise — do not report.',
            'Readability sometimes favors explicit chains; performance findings must still justify themselves.',
            '`toArray()` vs `all()` are semantically different (recursive conversion vs raw items); never swap them blindly.',
        ],
        'references' => [
            'https://laravel.com/docs/collections#available-methods',
            'https://laravel.com/docs/collections#lazy-collections',
        ],
        'applicability' => [],
    ],
];
